-- F13: curated drink list. Read-only to clients; maintained via migrations
-- (free-text names that recur get promoted here by hand — no request queue).
-- normalized_name is the identity key; the normalization rule everywhere
-- (here, the entries trigger, and web/lib/normalize.ts) is:
--   lower(regexp_replace(btrim(x), '\s+', ' ', 'g'))
create table public.drinks (
  id bigint generated always as identity primary key,
  name text not null,
  normalized_name text not null unique,
  is_alcoholic boolean not null,
  created_at timestamptz not null default now()
);

alter table public.drinks enable row level security;

-- Explicit grant: default ACLs on newer stacks give client roles no DML on
-- postgres-created tables (RLS alone isn't enough — no grant means 42501).
grant select on public.drinks to authenticated;

create policy "authenticated read drinks" on public.drinks
  for select to authenticated using (true);

insert into public.drinks (name, normalized_name, is_alcoholic) values
  -- beer & cider
  ('Lager', 'lager', true),
  ('IPA', 'ipa', true),
  ('Pale Ale', 'pale ale', true),
  ('Stout', 'stout', true),
  ('Porter', 'porter', true),
  ('Pilsner', 'pilsner', true),
  ('Wheat Beer', 'wheat beer', true),
  ('Sour Beer', 'sour beer', true),
  ('Amber Ale', 'amber ale', true),
  ('Cider', 'cider', true),
  -- wine & adjacent
  ('Red Wine', 'red wine', true),
  ('White Wine', 'white wine', true),
  ('Rosé', 'rosé', true),
  ('Champagne', 'champagne', true),
  ('Prosecco', 'prosecco', true),
  ('Sangria', 'sangria', true),
  ('Sake', 'sake', true),
  ('Soju', 'soju', true),
  -- spirits & shots
  ('Vodka', 'vodka', true),
  ('Gin', 'gin', true),
  ('Tequila', 'tequila', true),
  ('Whiskey', 'whiskey', true),
  ('Bourbon', 'bourbon', true),
  ('Scotch', 'scotch', true),
  ('Rum', 'rum', true),
  ('Mezcal', 'mezcal', true),
  ('Brandy', 'brandy', true),
  ('Fireball', 'fireball', true),
  ('Jägermeister', 'jägermeister', true),
  ('Jägerbomb', 'jägerbomb', true),
  ('Green Tea Shot', 'green tea shot', true),
  ('Lemon Drop Shot', 'lemon drop shot', true),
  ('Pickleback', 'pickleback', true),
  -- cocktails & mixed
  ('Margarita', 'margarita', true),
  ('Mojito', 'mojito', true),
  ('Negroni', 'negroni', true),
  ('Old Fashioned', 'old fashioned', true),
  ('Manhattan', 'manhattan', true),
  ('Martini', 'martini', true),
  ('Espresso Martini', 'espresso martini', true),
  ('Cosmopolitan', 'cosmopolitan', true),
  ('Daiquiri', 'daiquiri', true),
  ('Piña Colada', 'piña colada', true),
  ('Mai Tai', 'mai tai', true),
  ('Moscow Mule', 'moscow mule', true),
  ('Paloma', 'paloma', true),
  ('Whiskey Sour', 'whiskey sour', true),
  ('Amaretto Sour', 'amaretto sour', true),
  ('Aperol Spritz', 'aperol spritz', true),
  ('Gin and Tonic', 'gin and tonic', true),
  ('Vodka Soda', 'vodka soda', true),
  ('Vodka Red Bull', 'vodka red bull', true),
  ('Rum and Coke', 'rum and coke', true),
  ('Jack and Coke', 'jack and coke', true),
  ('Long Island Iced Tea', 'long island iced tea', true),
  ('Bloody Mary', 'bloody mary', true),
  ('Mimosa', 'mimosa', true),
  ('White Russian', 'white russian', true),
  ('Tom Collins', 'tom collins', true),
  ('French 75', 'french 75', true),
  ('Dark and Stormy', 'dark and stormy', true),
  ('Sex on the Beach', 'sex on the beach', true),
  ('Tequila Sunrise', 'tequila sunrise', true),
  ('Michelada', 'michelada', true),
  ('Hard Seltzer', 'hard seltzer', true),
  ('Hard Kombucha', 'hard kombucha', true),
  -- non-alcoholic
  ('Water', 'water', false),
  ('Sparkling Water', 'sparkling water', false),
  ('Coke', 'coke', false),
  ('Diet Coke', 'diet coke', false),
  ('Sprite', 'sprite', false),
  ('Ginger Ale', 'ginger ale', false),
  ('Ginger Beer', 'ginger beer', false),
  ('Root Beer', 'root beer', false),
  ('Lemonade', 'lemonade', false),
  ('Iced Tea', 'iced tea', false),
  ('Arnold Palmer', 'arnold palmer', false),
  ('Orange Juice', 'orange juice', false),
  ('Cranberry Juice', 'cranberry juice', false),
  ('Red Bull', 'red bull', false),
  ('Coffee', 'coffee', false),
  ('Espresso', 'espresso', false),
  ('Latte', 'latte', false),
  ('Matcha', 'matcha', false),
  ('Tea', 'tea', false),
  ('Hot Chocolate', 'hot chocolate', false),
  ('Kombucha', 'kombucha', false),
  ('Bubble Tea', 'bubble tea', false),
  ('Virgin Mojito', 'virgin mojito', false),
  ('Shirley Temple', 'shirley temple', false),
  ('Non-Alcoholic Beer', 'non-alcoholic beer', false),
  -- classics sourced from drinkoftheweek.com's A-Z list (one-time pull;
  -- user-requested exception to the "no scraped source" scope note)
  ('AMF', 'amf', true),
  ('Alabama Slammer', 'alabama slammer', true),
  ('Appletini', 'appletini', true),
  ('B-52', 'b-52', true),
  ('Bahama Mama', 'bahama mama', true),
  ('Bay Breeze', 'bay breeze', true),
  ('Bellini', 'bellini', true),
  ('Black Russian', 'black russian', true),
  ('Bloody Maria', 'bloody maria', true),
  ('Blue Hawaiian', 'blue hawaiian', true),
  ('Boilermaker', 'boilermaker', true),
  ('Brandy Alexander', 'brandy alexander', true),
  ('Buttery Nipple', 'buttery nipple', true),
  ('Caipirinha', 'caipirinha', true),
  ('Champagne Cocktail', 'champagne cocktail', true),
  ('Cuba Libre', 'cuba libre', true),
  ('Fuzzy Navel', 'fuzzy navel', true),
  ('Gimlet', 'gimlet', true),
  ('Gin Fizz', 'gin fizz', true),
  ('Godfather', 'godfather', true),
  ('Grasshopper', 'grasshopper', true),
  ('Greyhound', 'greyhound', true),
  ('Harvey Wallbanger', 'harvey wallbanger', true),
  ('Hot Toddy', 'hot toddy', true),
  ('Hurricane', 'hurricane', true),
  ('Irish Coffee', 'irish coffee', true),
  ('Kamikaze', 'kamikaze', true),
  ('Kir Royale', 'kir royale', true),
  ('Lemon Drop', 'lemon drop', true),
  ('Madras', 'madras', true),
  ('Mind Eraser', 'mind eraser', true),
  ('Mint Julep', 'mint julep', true),
  ('Mudslide', 'mudslide', true),
  ('Planter''s Punch', 'planter''s punch', true),
  ('Rusty Nail', 'rusty nail', true),
  ('Salty Dog', 'salty dog', true),
  ('Sazerac', 'sazerac', true),
  ('Screwdriver', 'screwdriver', true),
  ('Sidecar', 'sidecar', true),
  ('Singapore Sling', 'singapore sling', true),
  ('Vesper', 'vesper', true),
  ('Washington Apple', 'washington apple', true),
  ('White Lady', 'white lady', true),
  ('Zombie', 'zombie', true);
